// <auto-generated />
using System;
using DAL.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(TecmeindbContext))]
    [Migration("20251102235123_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb3_general_ci")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb3");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Entity.AuditoriaEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DireccionIp")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AuditoriaEventos");
                });

            modelBuilder.Entity("Entity.Canton", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("codigo");

                    b.Property<short?>("EstaActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("estaActivo");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("SecProvincia")
                        .HasColumnType("int")
                        .HasColumnName("secProvincia");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SecProvincia" }, "Fk_Provincia_Canton");

                    b.ToTable("canton", (string)null);
                });

            modelBuilder.Entity("Entity.Catalogo", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<short?>("EstaActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("estaActivo");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaRegistro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreArchivo");

                    b.Property<string>("UrlCatalogo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("urlCatalogo");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.ToTable("catalogo", (string)null);
                });

            modelBuilder.Entity("Entity.Cliente", b =>
                {
                    b.Property<int>("SecCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SecCliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SecCliente"));

                    b.Property<bool?>("EstaActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EstaActivo");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NumeroCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NumeroCliente");

                    b.Property<int>("SecConstructora")
                        .HasColumnType("int")
                        .HasColumnName("SecConstructora");

                    b.HasKey("SecCliente")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SecConstructora" }, "FK_Cliente_Constructora_idx")
                        .IsUnique();

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("Entity.Constructora", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("Administrador")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("administrador");

                    b.Property<string>("Atencion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("atencion");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("CorreoAdministrador")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correoAdministrador");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("direccion");

                    b.Property<short?>("EstaActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("estaActivo");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("telefono");

                    b.Property<string>("TelefonoAdministrador")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("telefonoAdministrador");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.ToTable("constructora", (string)null);
                });

            modelBuilder.Entity("Entity.Contacto", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Correo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("correo");

                    b.Property<short?>("EstaActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("estaActivo");

                    b.Property<string>("Nombres")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("SecConstructora")
                        .HasColumnType("int")
                        .HasColumnName("secConstructora");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("telefono");

                    b.Property<string>("Titulo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("titulo");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SecConstructora" }, "FK_Contacto_Constructora_idx");

                    b.ToTable("contacto", (string)null);
                });

            modelBuilder.Entity("Entity.Contactovisita", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<short>("EstaActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("estaActivo");

                    b.Property<int>("SecContacto")
                        .HasColumnType("int")
                        .HasColumnName("secContacto");

                    b.Property<int>("SecVisita")
                        .HasColumnType("int")
                        .HasColumnName("secVisita");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SecContacto" }, "Fk_Contacto_ContactoVisita");

                    b.HasIndex(new[] { "SecVisita" }, "Fk_Contacto_Visita");

                    b.ToTable("contactovisita", (string)null);
                });

            modelBuilder.Entity("Entity.Contrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdContrato");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdContrato"));

                    b.Property<bool?>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EsActivo");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime>("FechaFirma")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaFirma");

                    b.Property<int>("IdCotizacion")
                        .HasColumnType("int")
                        .HasColumnName("IdCotizacion");

                    b.Property<int>("IdUsuarioCarga")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioCarga");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NombreArchivo");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("RutaArchivo");

                    b.Property<int>("SecCliente")
                        .HasColumnType("int");

                    b.HasKey("IdContrato")
                        .HasName("PRIMARY");

                    b.HasIndex("SecCliente");

                    b.HasIndex(new[] { "IdCotizacion" }, "FK_Contrato_Cotizacion_idx");

                    b.HasIndex(new[] { "IdUsuarioCarga" }, "FK_Contrato_Usuario_idx");

                    b.ToTable("contrato", (string)null);
                });

            modelBuilder.Entity("Entity.Cotizacion", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<bool>("Confirmacion")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("confirmacion");

                    b.Property<bool>("EnviadoCliente")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enviadoCliente");

                    b.Property<bool>("EnviadoProveedor")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enviadoProveedor");

                    b.Property<short?>("EstaActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("estaActivo");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaModificacion");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaRegistro");

                    b.Property<int?>("SecCotizacionOriginal")
                        .HasColumnType("int")
                        .HasColumnName("secCotizacionOriginal");

                    b.Property<int?>("SecUsuario")
                        .HasColumnType("int")
                        .HasColumnName("secUsuario");

                    b.Property<int?>("SecUsuarioModifica")
                        .HasColumnType("int")
                        .HasColumnName("secUsuarioModifica");

                    b.Property<int>("SecVisita")
                        .HasColumnType("int")
                        .HasColumnName("secVisita");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TotalConImpuestos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("totalConImpuestos");

                    b.Property<decimal>("ValorIVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valorIVA");

                    b.Property<decimal>("ValorImportacion")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valorImportacion");

                    b.Property<decimal>("ValorImpuestos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valorImpuestos");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.HasIndex("SecCotizacionOriginal");

                    b.HasIndex("SecUsuario");

                    b.HasIndex("SecUsuarioModifica");

                    b.HasIndex(new[] { "SecVisita" }, "FK_Cotizacion_Visita_idx");

                    b.ToTable("cotizacion", (string)null);
                });

            modelBuilder.Entity("Entity.Cotizaciondetalle", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("DetalleEquipo")
                        .HasColumnType("longtext")
                        .HasColumnName("DetalleEquipo");

                    b.Property<short?>("EstaActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("EstaActivo");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaRegistro");

                    b.Property<decimal>("MargenGanancia")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("MargenGanancia");

                    b.Property<int>("SecCotizacion")
                        .HasColumnType("int")
                        .HasColumnName("SecCotizacion");

                    b.Property<int?>("SecEquipoVisita")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Total");

                    b.Property<decimal>("ValorCompra")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("ValorCompra");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.HasIndex("SecCotizacion");

                    b.ToTable("cotizaciondetalle", (string)null);
                });

            modelBuilder.Entity("Entity.Cuota", b =>
                {
                    b.Property<int>("IdCuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCuota");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCuota"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaRegistro");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaVencimiento");

                    b.Property<int>("IdPlanDePago")
                        .HasColumnType("int")
                        .HasColumnName("IdPlanDePago");

                    b.Property<decimal>("MontoEsperado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MontoEsperado");

                    b.Property<decimal?>("MontoPagado")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("int")
                        .HasColumnName("NumeroCuota");

                    b.HasKey("IdCuota")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPlanDePago" }, "FK_Cuota_PlanDePago_idx");

                    b.ToTable("cuota", (string)null);
                });

            modelBuilder.Entity("Entity.DiccionarioParametro", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Parametro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Parametro" }, "UQ_DiccionarioParametro_Parametro")
                        .IsUnique();

                    b.ToTable("diccionarioparametro", (string)null);
                });

            modelBuilder.Entity("Entity.Empresa", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("CodigoOperador")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("codigoOperador");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("direccion");

                    b.Property<short?>("EstaActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("estaActivo");

                    b.Property<string>("Identificacion")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreLogo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombreLogo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("telefono");

                    b.Property<string>("UrlLogo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("urlLogo");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.ToTable("empresa", (string)null);
                });

            modelBuilder.Entity("Entity.Empresacorreo", b =>
                {
                    b.Property<int>("SecEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("alias");

                    b.Property<string>("Clave")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("clave");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<short?>("EstaActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("estaActivo");

                    b.Property<string>("Host")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("host");

                    b.Property<int?>("Puerto")
                        .HasColumnType("int")
                        .HasColumnName("puerto");

                    b.HasKey("SecEmpresa")
                        .HasName("PRIMARY");

                    b.ToTable("empresacorreo", (string)null);
                });

            modelBuilder.Entity("Entity.Empresastorage", b =>
                {
                    b.Property<int>("SecEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("secEmpresa");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("apiKey");

                    b.Property<string>("CarpetaLogo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("carpetaLogo");

                    b.Property<string>("CarpetaProducto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("carpetaProducto");

                    b.Property<string>("CarpetaUsuario")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("carpetaUsuario");

                    b.Property<string>("Clave")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("clave");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<short?>("EstaActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("estaActivo");

                    b.Property<string>("Ruta")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ruta");

                    b.HasKey("SecEmpresa")
                        .HasName("PRIMARY");

                    b.ToTable("empresastorage", (string)null);
                });

            modelBuilder.Entity("Entity.Equiposvisita", b =>
                {
                    b.Property<int>("Secuencial")
                        .HasColumnType("int")
                        .HasColumnName("secuencial");

                    b.Property<int?>("AlturaEntrePisos")
                        .HasColumnType("int")
                        .HasColumnName("alturaEntrePisos");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int")
                        .HasColumnName("capacidad");

                    b.Property<int?>("DimencionEntrada")
                        .HasColumnType("int")
                        .HasColumnName("dimencionEntrada");

                    b.Property<string>("Embarque")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("embarque");

                    b.Property<string>("Energia")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("energia");

                    b.Property<short>("EstaActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("estaActivo");

                    b.Property<int?>("Foso")
                        .HasColumnType("int")
                        .HasColumnName("foso");

                    b.Property<int?>("IngresosFrontales")
                        .HasColumnType("int")
                        .HasColumnName("ingresosFrontales");

                    b.Property<int?>("IngresosPosteriores")
                        .HasColumnType("int")
                        .HasColumnName("ingresosPosteriores");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("marca");

                    b.Property<string>("MaterialPuertas")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("materialPuertas");

                    b.Property<string>("MedidasAfducto")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("medidasAFDucto");

                    b.Property<string>("NombresParadas")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombresParadas");

                    b.Property<int?>("NumeroParadas")
                        .HasColumnType("int")
                        .HasColumnName("numeroParadas");

                    b.Property<int?>("NumeroPersonas")
                        .HasColumnType("int")
                        .HasColumnName("numeroPersonas");

                    b.Property<int?>("Recorrido")
                        .HasColumnType("int")
                        .HasColumnName("recorrido");

                    b.Property<string>("SalaControl")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("salaControl");

                    b.Property<string>("SalaMaquinas")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("salaMaquinas");

                    b.Property<int>("SecVisita")
                        .HasColumnType("int")
                        .HasColumnName("secVisita");

                    b.Property<string>("Sistema")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sistema");

                    b.Property<int?>("SobreRecorrido")
                        .HasColumnType("int");

                    b.Property<string>("TipoDucto")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipoDucto");

                    b.Property<string>("TipoEquipo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("tipoEquipo");

                    b.Property<string>("TipoMotor")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipoMotor");

                    b.Property<decimal?>("Velocidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("velocidad");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Secuencial" }, "secuencial_UNIQUE")
                        .IsUnique();

                    b.ToTable("equiposvisita", (string)null);
                });

            modelBuilder.Entity("Entity.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Descripcion");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EstaActivo");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("Orden");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("etapa", (string)null);
                });

            modelBuilder.Entity("Entity.FormaPago", b =>
                {
                    b.Property<int>("SecFormaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SecFormaPago");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SecFormaPago"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<short>("EstaActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("EstaActivo");

                    b.HasKey("SecFormaPago")
                        .HasName("PRIMARY");

                    b.ToTable("formapago", (string)null);
                });

            modelBuilder.Entity("Entity.FormatoNumeroCliente", b =>
                {
                    b.Property<int>("SecFormatoNumeroCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SecFormatoNumeroCliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SecFormatoNumeroCliente"));

                    b.Property<string>("Formato")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Formato");

                    b.Property<int>("LongitudNumero")
                        .HasColumnType("int");

                    b.Property<int>("NumeroInicio")
                        .HasColumnType("int")
                        .HasColumnName("NumeroInicio");

                    b.Property<int>("SecEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("SecEmpresa");

                    b.Property<bool>("UsaFormato")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("UsaFormato");

                    b.HasKey("SecFormatoNumeroCliente")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SecEmpresa" }, "FK_FormatoNumeroCliente_Empresa_idx");

                    b.ToTable("formatonumerocliente", (string)null);
                });

            modelBuilder.Entity("Entity.Impuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Codigo");

                    b.Property<string>("CodigoSri")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CodigoSri");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<decimal?>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Porcentaje");

                    b.Property<int>("SecTipoImpuesto")
                        .HasColumnType("int")
                        .HasColumnName("SecTipoImpuesto");

                    b.Property<decimal?>("ValorFijo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorFijo");

                    b.Property<bool>("Vigente")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Vigente");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("SecTipoImpuesto");

                    b.ToTable("impuesto", (string)null);
                });

            modelBuilder.Entity("Entity.ImpuestoCotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseImponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BaseImponible");

                    b.Property<bool>("Exento")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Exento");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FechaRegistro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ImpuestoId")
                        .HasColumnType("int")
                        .HasColumnName("ImpuestoId");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext")
                        .HasColumnName("Observaciones");

                    b.Property<int>("SecCotizacion")
                        .HasColumnType("int")
                        .HasColumnName("SecCotizacion");

                    b.Property<decimal>("ValorImpuesto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorImpuesto");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("ImpuestoId");

                    b.HasIndex("SecCotizacion");

                    b.ToTable("impuestocotizacion", (string)null);
                });

            modelBuilder.Entity("Entity.Menu", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("Controlador")
                        .HasMaxLength(130)
                        .HasColumnType("varchar(130)")
                        .HasColumnName("controlador");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(130)
                        .HasColumnType("varchar(130)")
                        .HasColumnName("descripcion");

                    b.Property<short?>("EsActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("esActivo");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaRegistro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Icono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("icono");

                    b.Property<bool>("MostrarEnMenu")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("PaginaAccion")
                        .HasMaxLength(130)
                        .HasColumnType("varchar(130)")
                        .HasColumnName("paginaAccion");

                    b.Property<int?>("SecMenuPadre")
                        .HasColumnType("int")
                        .HasColumnName("secMenuPadre");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SecMenuPadre" }, "FK_Menu_Menu_idx");

                    b.ToTable("menu", (string)null);
                });

            modelBuilder.Entity("Entity.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPago");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<string>("ComprobanteNombre")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ComprobanteNombre");

                    b.Property<string>("ComprobanteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ComprobanteUrl");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EstaActivo");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaPago");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaRegistro");

                    b.Property<int>("IdPlanDePago")
                        .HasColumnType("int")
                        .HasColumnName("IdPlanDePago");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Monto");

                    b.Property<int>("RegistradoPorUsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("RegistradoPorUsuarioId");

                    b.HasKey("IdPago")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPlanDePago" }, "FK_Pago_PlanDePago_idx");

                    b.HasIndex(new[] { "RegistradoPorUsuarioId" }, "FK_Pago_Usuario_idx");

                    b.ToTable("pago", (string)null);
                });

            modelBuilder.Entity("Entity.Parroquia", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("codigo");

                    b.Property<short?>("EstaActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("estaActivo");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("SecCanton")
                        .HasColumnType("int")
                        .HasColumnName("secCanton");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SecCanton" }, "FK_Parroquia_Canton_idx");

                    b.ToTable("parroquia", (string)null);
                });

            modelBuilder.Entity("Entity.Permiso", b =>
                {
                    b.Property<string>("IdPermiso")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("IdPermiso");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Descripcion");

                    b.HasKey("IdPermiso")
                        .HasName("PRIMARY");

                    b.ToTable("permiso", (string)null);
                });

            modelBuilder.Entity("Entity.PlanDePago", b =>
                {
                    b.Property<int>("IdPlanDePago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPlanDePago");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPlanDePago"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EstaActivo");

                    b.Property<DateTime?>("FechaAnticipo")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaAnticipo");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaPrimeraCuota")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaPrimeraCuota");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaRegistro");

                    b.Property<int>("IdContrato")
                        .HasColumnType("int")
                        .HasColumnName("IdContrato");

                    b.Property<int>("NumeroCuotas")
                        .HasColumnType("int")
                        .HasColumnName("NumeroCuotas");

                    b.Property<int>("SecFormaPago")
                        .HasColumnType("int")
                        .HasColumnName("SecFormaPago");

                    b.Property<decimal>("ValorAnticipo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorAnticipo");

                    b.Property<decimal>("ValorContrato")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorContrato");

                    b.HasKey("IdPlanDePago")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdContrato" }, "FK_PlanDePago_Contrato_idx")
                        .IsUnique();

                    b.HasIndex(new[] { "SecFormaPago" }, "FK_PlanDePago_FormaPago_idx");

                    b.ToTable("plandepago", (string)null);
                });

            modelBuilder.Entity("Entity.PlantillaPreContrato", b =>
                {
                    b.Property<int>("SecPlantillaPreContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SecPlantillaPreContrato");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SecPlantillaPreContrato"));

                    b.Property<int?>("EstaActivo")
                        .HasColumnType("int")
                        .HasColumnName("EstaActivo");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NumeracionInicial")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SecTipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("SecTipoDocumento");

                    b.HasKey("SecPlantillaPreContrato")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SecTipoDocumento" }, "FK_PlantillaPreContrato_TipoDocumento_idx");

                    b.ToTable("plantillaprecontrato", (string)null);
                });

            modelBuilder.Entity("Entity.PlantillaPreContratoParrafo", b =>
                {
                    b.Property<int>("SecPlantillaPreContratoParrafo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SecPlantillaPreContratoParrafo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SecPlantillaPreContratoParrafo"));

                    b.Property<string>("Contenido")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EstaActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EstaActivo");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("Orden");

                    b.Property<int>("SecPlantillaPreContrato")
                        .HasColumnType("int")
                        .HasColumnName("SecPlantillaPreContrato");

                    b.HasKey("SecPlantillaPreContratoParrafo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SecPlantillaPreContrato" }, "IX_plantillaprecontratoparrafo_plantilla");

                    b.ToTable("plantillaprecontratoparrafo", (string)null);
                });

            modelBuilder.Entity("Entity.PolizaGarantia", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Secuencial");

                    b.ToTable("PolizaGarantia");
                });

            modelBuilder.Entity("Entity.PreContrato", b =>
                {
                    b.Property<int>("SecPreContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SecPreContrato");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SecPreContrato"));

                    b.Property<int>("AniosGarantia")
                        .HasColumnType("int")
                        .HasColumnName("AniosGarantia");

                    b.Property<int>("Dias")
                        .HasColumnType("int")
                        .HasColumnName("Dias");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EstaActivo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaRegistro");

                    b.Property<int>("MesesGarantia")
                        .HasColumnType("int")
                        .HasColumnName("MesesGarantia");

                    b.Property<string>("PeriodoMantenimiento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PeriodoMantenimiento");

                    b.Property<string>("PolizaGarantia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PolizaGarantia");

                    b.Property<int>("SecCotizacion")
                        .HasColumnType("int")
                        .HasColumnName("SecCotizacion");

                    b.Property<int>("SecPlantillaPreContrato")
                        .HasColumnType("int")
                        .HasColumnName("SecPlantillaPreContrato");

                    b.Property<int>("SecUsuarioCrea")
                        .HasColumnType("int")
                        .HasColumnName("SecUsuarioCrea");

                    b.Property<string>("TipoDias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TipoDias");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("Version");

                    b.HasKey("SecPreContrato")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SecCotizacion" }, "FK_PreContrato_Cotizacion_idx");

                    b.HasIndex(new[] { "SecPlantillaPreContrato" }, "FK_PreContrato_Plantilla_idx");

                    b.HasIndex(new[] { "SecUsuarioCrea" }, "FK_PreContrato_Usuario_idx");

                    b.ToTable("precontrato", (string)null);
                });

            modelBuilder.Entity("Entity.PreContratoCompromisoPago", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("int");

                    b.Property<int>("SecPreContrato")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Secuencial");

                    b.HasIndex("SecPreContrato");

                    b.ToTable("PreContratoCompromisoPagos");
                });

            modelBuilder.Entity("Entity.PreContratoParrafo", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("SecPreContrato")
                        .HasColumnType("int");

                    b.HasKey("Secuencial");

                    b.HasIndex("SecPreContrato");

                    b.ToTable("precontratoparrafo");
                });

            modelBuilder.Entity("Entity.Provincia", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("codigo");

                    b.Property<short?>("EstaActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("estaActivo");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.ToTable("provincia", (string)null);
                });

            modelBuilder.Entity("Entity.Rol", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<short?>("EsActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("esActivo");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaRegistro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("Entity.RolMenu", b =>
                {
                    b.Property<int>("SecRol")
                        .HasColumnType("int")
                        .HasColumnName("secRol");

                    b.Property<int>("SecMenu")
                        .HasColumnType("int")
                        .HasColumnName("secMenu");

                    b.Property<bool>("Actualizar")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Actualizar");

                    b.Property<bool>("Crear")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Crear");

                    b.Property<bool>("Eliminar")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Eliminar");

                    b.Property<bool>("Leer")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Leer");

                    b.Property<bool>("VerMenu")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("SecRol", "SecMenu");

                    b.HasIndex(new[] { "SecMenu" }, "FK_Menu_Rol_idx");

                    b.HasIndex(new[] { "SecRol" }, "FK_Rol_Menu_idx");

                    b.ToTable("rolmenu", (string)null);
                });

            modelBuilder.Entity("Entity.RolPermiso", b =>
                {
                    b.Property<int>("SecRol")
                        .HasColumnType("int");

                    b.Property<string>("IdPermiso")
                        .HasColumnType("varchar(100)");

                    b.HasKey("SecRol", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("rolpermiso", (string)null);
                });

            modelBuilder.Entity("Entity.Seguimiento", b =>
                {
                    b.Property<int>("SecSeguimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SecSeguimiento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SecSeguimiento"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Accion");

                    b.Property<bool>("AceptacionCliente")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("AceptacionCliente");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Detalle");

                    b.Property<DateTime>("FechaAccion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaAccion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FechaRegistro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SecCotizacion")
                        .HasColumnType("int")
                        .HasColumnName("SecCotizacion");

                    b.HasKey("SecSeguimiento")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SecCotizacion" }, "FK_Seguimiento_Cotizacion_idx");

                    b.ToTable("seguimiento", (string)null);
                });

            modelBuilder.Entity("Entity.TipoDocumento", b =>
                {
                    b.Property<int>("SecTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SecTipoDocumento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SecTipoDocumento"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("EstaActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EstaActivo");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime");

                    b.HasKey("SecTipoDocumento")
                        .HasName("PRIMARY");

                    b.ToTable("tipodocumento", (string)null);
                });

            modelBuilder.Entity("Entity.TipoImpuesto", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<bool>("EsImportacion")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EsImportacion");

                    b.Property<bool>("EsIva")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EsIva");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EstaActivo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.ToTable("tipoimpuesto", (string)null);
                });

            modelBuilder.Entity("Entity.Usuario", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("Clave")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("clave");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correo");

                    b.Property<short?>("EsActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("esActivo");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaRegistro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreFoto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombreFoto");

                    b.Property<int?>("SecRol")
                        .HasColumnType("int")
                        .HasColumnName("secRol");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("telefono");

                    b.Property<string>("UrlFoto")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("urlFoto");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SecRol" }, "Fk_Rol_Usuario_idx");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Entity.Visita", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("secuencial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("detalle");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("direccion");

                    b.Property<short?>("EstaActivo")
                        .HasColumnType("smallint")
                        .HasColumnName("estaActivo");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaRegistro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaSiguienteVisita")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaSiguienteVisita");

                    b.Property<string>("GeoUbicacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("geoUbicacion");

                    b.Property<int>("IdEtapa")
                        .HasColumnType("int")
                        .HasColumnName("IdEtapa");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<int?>("SecCanton")
                        .HasColumnType("int")
                        .HasColumnName("secCanton");

                    b.Property<int?>("SecConstructora")
                        .HasColumnType("int");

                    b.Property<int?>("SecEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("SecEmpresa");

                    b.Property<int?>("SecParroquia")
                        .HasColumnType("int")
                        .HasColumnName("secParroquia");

                    b.Property<int?>("SecProvincia")
                        .HasColumnType("int")
                        .HasColumnName("secProvincia");

                    b.Property<int>("SecUsuario")
                        .HasColumnType("int")
                        .HasColumnName("secUsuario");

                    b.HasKey("Secuencial")
                        .HasName("PRIMARY");

                    b.HasIndex("IdEtapa");

                    b.HasIndex("SecConstructora");

                    b.HasIndex("SecEmpresa");

                    b.HasIndex(new[] { "SecCanton" }, "Fk_Visita_Canton");

                    b.HasIndex(new[] { "SecParroquia" }, "Fk_Visita_Parroquia");

                    b.HasIndex(new[] { "SecProvincia" }, "Fk_Visita_Provincia");

                    b.HasIndex(new[] { "SecUsuario" }, "Fk_Visita_Usuario_idx");

                    b.ToTable("visita", (string)null);
                });

            modelBuilder.Entity("Entity.Canton", b =>
                {
                    b.HasOne("Entity.Provincia", "SecProvinciaNavigation")
                        .WithMany("Cantons")
                        .HasForeignKey("SecProvincia")
                        .IsRequired()
                        .HasConstraintName("Fk_Provincia_Canton");

                    b.Navigation("SecProvinciaNavigation");
                });

            modelBuilder.Entity("Entity.Cliente", b =>
                {
                    b.HasOne("Entity.Constructora", "SecConstructoraNavigation")
                        .WithOne("Cliente")
                        .HasForeignKey("Entity.Cliente", "SecConstructora")
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Constructora");

                    b.Navigation("SecConstructoraNavigation");
                });

            modelBuilder.Entity("Entity.Contacto", b =>
                {
                    b.HasOne("Entity.Constructora", "SecConstructoraNavigation")
                        .WithMany("Contactos")
                        .HasForeignKey("SecConstructora")
                        .IsRequired()
                        .HasConstraintName("FK_Contacto_Constructora");

                    b.Navigation("SecConstructoraNavigation");
                });

            modelBuilder.Entity("Entity.Contactovisita", b =>
                {
                    b.HasOne("Entity.Contacto", "SecContactoNavigation")
                        .WithMany("Contactovisita")
                        .HasForeignKey("SecContacto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Fk_Contacto_ContactoVisita");

                    b.HasOne("Entity.Visita", "SecVisitaNavigation")
                        .WithMany("Contactovisita")
                        .HasForeignKey("SecVisita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Fk_Visita_ContactoVisita");

                    b.Navigation("SecContactoNavigation");

                    b.Navigation("SecVisitaNavigation");
                });

            modelBuilder.Entity("Entity.Contrato", b =>
                {
                    b.HasOne("Entity.Cotizacion", "IdCotizacionNavigation")
                        .WithMany()
                        .HasForeignKey("IdCotizacion")
                        .IsRequired()
                        .HasConstraintName("FK_Contrato_Cotizacion");

                    b.HasOne("Entity.Usuario", "IdUsuarioCargaNavigation")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCarga")
                        .IsRequired()
                        .HasConstraintName("FK_Contrato_Usuario");

                    b.HasOne("Entity.Cliente", "SecClienteNavigation")
                        .WithMany("Contratos")
                        .HasForeignKey("SecCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Contrato_Cliente");

                    b.Navigation("IdCotizacionNavigation");

                    b.Navigation("IdUsuarioCargaNavigation");

                    b.Navigation("SecClienteNavigation");
                });

            modelBuilder.Entity("Entity.Cotizacion", b =>
                {
                    b.HasOne("Entity.Cotizacion", "SecCotizacionOriginalNavigation")
                        .WithMany()
                        .HasForeignKey("SecCotizacionOriginal")
                        .HasConstraintName("FK_Cotizacion_CotizacionOriginal");

                    b.HasOne("Entity.Usuario", "SecUsuarioNavigation")
                        .WithMany()
                        .HasForeignKey("SecUsuario")
                        .HasConstraintName("FK_Cotizacion_Usuario");

                    b.HasOne("Entity.Usuario", "SecUsuarioModificaNavigation")
                        .WithMany()
                        .HasForeignKey("SecUsuarioModifica")
                        .HasConstraintName("FK_Cotizacion_UsuarioModifica");

                    b.HasOne("Entity.Visita", "SecVisitaNavigation")
                        .WithMany()
                        .HasForeignKey("SecVisita")
                        .IsRequired()
                        .HasConstraintName("FK_Cotizacion_Visita");

                    b.Navigation("SecCotizacionOriginalNavigation");

                    b.Navigation("SecUsuarioModificaNavigation");

                    b.Navigation("SecUsuarioNavigation");

                    b.Navigation("SecVisitaNavigation");
                });

            modelBuilder.Entity("Entity.Cotizaciondetalle", b =>
                {
                    b.HasOne("Entity.Cotizacion", "SecCotizacionNavigation")
                        .WithMany("Cotizaciondetalles")
                        .HasForeignKey("SecCotizacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Cotizaciondetalle_Cotizacion");

                    b.Navigation("SecCotizacionNavigation");
                });

            modelBuilder.Entity("Entity.Cuota", b =>
                {
                    b.HasOne("Entity.PlanDePago", "IdPlanDePagoNavigation")
                        .WithMany("Cuotas")
                        .HasForeignKey("IdPlanDePago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Cuota_PlanDePago");

                    b.Navigation("IdPlanDePagoNavigation");
                });

            modelBuilder.Entity("Entity.Empresacorreo", b =>
                {
                    b.HasOne("Entity.Empresa", "SecEmpresaNavigation")
                        .WithOne("Empresacorreo")
                        .HasForeignKey("Entity.Empresacorreo", "SecEmpresa")
                        .IsRequired()
                        .HasConstraintName("Fk_Empresa_EmpCorreo");

                    b.Navigation("SecEmpresaNavigation");
                });

            modelBuilder.Entity("Entity.Empresastorage", b =>
                {
                    b.HasOne("Entity.Empresa", "SecEmpresaNavigation")
                        .WithOne("Empresastorage")
                        .HasForeignKey("Entity.Empresastorage", "SecEmpresa")
                        .IsRequired()
                        .HasConstraintName("empresastorage_ibfk_1");

                    b.Navigation("SecEmpresaNavigation");
                });

            modelBuilder.Entity("Entity.FormatoNumeroCliente", b =>
                {
                    b.HasOne("Entity.Empresa", "SecEmpresaNavigation")
                        .WithMany("FormatosNumeroCliente")
                        .HasForeignKey("SecEmpresa")
                        .IsRequired()
                        .HasConstraintName("FK_FormatoNumeroCliente_Empresa");

                    b.Navigation("SecEmpresaNavigation");
                });

            modelBuilder.Entity("Entity.Impuesto", b =>
                {
                    b.HasOne("Entity.TipoImpuesto", "SecTipoImpuestoNavigation")
                        .WithMany()
                        .HasForeignKey("SecTipoImpuesto")
                        .IsRequired()
                        .HasConstraintName("FK_Impuesto_TipoImpuesto");

                    b.Navigation("SecTipoImpuestoNavigation");
                });

            modelBuilder.Entity("Entity.ImpuestoCotizacion", b =>
                {
                    b.HasOne("Entity.Impuesto", "ImpuestoNavigation")
                        .WithMany("ImpuestoCotizacion")
                        .HasForeignKey("ImpuestoId")
                        .IsRequired()
                        .HasConstraintName("FK_ImpuestoCotizacion_Impuesto");

                    b.HasOne("Entity.Cotizacion", "SecCotizacionNavigation")
                        .WithMany("ImpuestoCotizaciones")
                        .HasForeignKey("SecCotizacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ImpuestoCotizacion_Cotizacion");

                    b.Navigation("ImpuestoNavigation");

                    b.Navigation("SecCotizacionNavigation");
                });

            modelBuilder.Entity("Entity.Menu", b =>
                {
                    b.HasOne("Entity.Menu", "SecMenuPadreNavigation")
                        .WithMany("InverseSecMenuPadreNavigation")
                        .HasForeignKey("SecMenuPadre")
                        .HasConstraintName("FK_Menu_Menu");

                    b.Navigation("SecMenuPadreNavigation");
                });

            modelBuilder.Entity("Entity.Pago", b =>
                {
                    b.HasOne("Entity.PlanDePago", "IdPlanDePagoNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdPlanDePago")
                        .IsRequired()
                        .HasConstraintName("FK_Pago_PlanDePago");

                    b.HasOne("Entity.Usuario", "RegistradoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RegistradoPorUsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Pago_Usuario");

                    b.Navigation("IdPlanDePagoNavigation");

                    b.Navigation("RegistradoPorUsuario");
                });

            modelBuilder.Entity("Entity.Parroquia", b =>
                {
                    b.HasOne("Entity.Canton", "SecCantonNavigation")
                        .WithMany("Parroquia")
                        .HasForeignKey("SecCanton")
                        .IsRequired()
                        .HasConstraintName("Fk_Canton_Parroquia");

                    b.Navigation("SecCantonNavigation");
                });

            modelBuilder.Entity("Entity.PlanDePago", b =>
                {
                    b.HasOne("Entity.Contrato", "IdContratoNavigation")
                        .WithOne("PlanDePagoNavigation")
                        .HasForeignKey("Entity.PlanDePago", "IdContrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.FormaPago", "SecFormaPagoNavigation")
                        .WithMany()
                        .HasForeignKey("SecFormaPago")
                        .IsRequired()
                        .HasConstraintName("FK_PlanDePago_FormaPago");

                    b.Navigation("IdContratoNavigation");

                    b.Navigation("SecFormaPagoNavigation");
                });

            modelBuilder.Entity("Entity.PlantillaPreContrato", b =>
                {
                    b.HasOne("Entity.TipoDocumento", "SecTipoDocumentoNavigation")
                        .WithMany()
                        .HasForeignKey("SecTipoDocumento")
                        .IsRequired()
                        .HasConstraintName("FK_PlantillaPreContrato_TipoDocumento");

                    b.Navigation("SecTipoDocumentoNavigation");
                });

            modelBuilder.Entity("Entity.PlantillaPreContratoParrafo", b =>
                {
                    b.HasOne("Entity.PlantillaPreContrato", "SecPlantillaPreContratoNavigation")
                        .WithMany("PlantillaPreContratoParrafos")
                        .HasForeignKey("SecPlantillaPreContrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_plantillaprecontratoparrafo_plantillaprecontrato");

                    b.Navigation("SecPlantillaPreContratoNavigation");
                });

            modelBuilder.Entity("Entity.PreContrato", b =>
                {
                    b.HasOne("Entity.Cotizacion", "SecCotizacionNavigation")
                        .WithMany()
                        .HasForeignKey("SecCotizacion")
                        .IsRequired()
                        .HasConstraintName("FK_PreContrato_Cotizacion");

                    b.HasOne("Entity.PlantillaPreContrato", "SecPlantillaPreContratoNavigation")
                        .WithMany()
                        .HasForeignKey("SecPlantillaPreContrato")
                        .IsRequired()
                        .HasConstraintName("FK_PreContrato_PlantillaPreContrato");

                    b.HasOne("Entity.Usuario", "SecUsuarioCreaNavigation")
                        .WithMany()
                        .HasForeignKey("SecUsuarioCrea")
                        .IsRequired()
                        .HasConstraintName("FK_PreContrato_Usuario");

                    b.Navigation("SecCotizacionNavigation");

                    b.Navigation("SecPlantillaPreContratoNavigation");

                    b.Navigation("SecUsuarioCreaNavigation");
                });

            modelBuilder.Entity("Entity.PreContratoCompromisoPago", b =>
                {
                    b.HasOne("Entity.PreContrato", "PreContratoNavigation")
                        .WithMany("PreContratoCompromisoPagos")
                        .HasForeignKey("SecPreContrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreContratoNavigation");
                });

            modelBuilder.Entity("Entity.PreContratoParrafo", b =>
                {
                    b.HasOne("Entity.PreContrato", "SecPreContratoNavigation")
                        .WithMany("PreContratoParrafos")
                        .HasForeignKey("SecPreContrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecPreContratoNavigation");
                });

            modelBuilder.Entity("Entity.RolMenu", b =>
                {
                    b.HasOne("Entity.Menu", "SecMenuNavigation")
                        .WithMany("Rolmenus")
                        .HasForeignKey("SecMenu")
                        .IsRequired()
                        .HasConstraintName("FK_Menu_Rol");

                    b.HasOne("Entity.Rol", "SecRolNavigation")
                        .WithMany("Rolmenus")
                        .HasForeignKey("SecRol")
                        .IsRequired()
                        .HasConstraintName("FK_Rol_Menu");

                    b.Navigation("SecMenuNavigation");

                    b.Navigation("SecRolNavigation");
                });

            modelBuilder.Entity("Entity.RolPermiso", b =>
                {
                    b.HasOne("Entity.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdPermiso")
                        .IsRequired()
                        .HasConstraintName("FK_RolPermiso_Permiso");

                    b.HasOne("Entity.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("SecRol")
                        .IsRequired()
                        .HasConstraintName("FK_RolPermiso_Rol");

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Entity.Seguimiento", b =>
                {
                    b.HasOne("Entity.Cotizacion", "SecCotizacionNavigation")
                        .WithMany("Seguimientos")
                        .HasForeignKey("SecCotizacion")
                        .IsRequired()
                        .HasConstraintName("FK_Seguimiento_Cotizacion");

                    b.Navigation("SecCotizacionNavigation");
                });

            modelBuilder.Entity("Entity.Usuario", b =>
                {
                    b.HasOne("Entity.Rol", "SecRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("SecRol")
                        .HasConstraintName("Fk_Rol_Usuario");

                    b.Navigation("SecRolNavigation");
                });

            modelBuilder.Entity("Entity.Visita", b =>
                {
                    b.HasOne("Entity.Etapa", "IdEtapaNavigation")
                        .WithMany()
                        .HasForeignKey("IdEtapa")
                        .IsRequired()
                        .HasConstraintName("FK_Visita_Etapa");

                    b.HasOne("Entity.Canton", "SecCantonNavigation")
                        .WithMany("Visita")
                        .HasForeignKey("SecCanton")
                        .HasConstraintName("Fk_Visita_Canton");

                    b.HasOne("Entity.Constructora", "SecConstructoraNavigation")
                        .WithMany()
                        .HasForeignKey("SecConstructora");

                    b.HasOne("Entity.Empresa", "SecEmpresaNavigation")
                        .WithMany()
                        .HasForeignKey("SecEmpresa")
                        .HasConstraintName("FK_Visita_Empresa");

                    b.HasOne("Entity.Parroquia", "SecParroquiaNavigation")
                        .WithMany("Visita")
                        .HasForeignKey("SecParroquia")
                        .HasConstraintName("Fk_Visita_Parroquia");

                    b.HasOne("Entity.Provincia", "SecProvinciaNavigation")
                        .WithMany("Visita")
                        .HasForeignKey("SecProvincia")
                        .HasConstraintName("Fk_Visita_Provincia");

                    b.HasOne("Entity.Usuario", "SecUsuarioNavigation")
                        .WithMany("Visita")
                        .HasForeignKey("SecUsuario")
                        .IsRequired()
                        .HasConstraintName("Fk_Visita_Usuario");

                    b.Navigation("IdEtapaNavigation");

                    b.Navigation("SecCantonNavigation");

                    b.Navigation("SecConstructoraNavigation");

                    b.Navigation("SecEmpresaNavigation");

                    b.Navigation("SecParroquiaNavigation");

                    b.Navigation("SecProvinciaNavigation");

                    b.Navigation("SecUsuarioNavigation");
                });

            modelBuilder.Entity("Entity.Canton", b =>
                {
                    b.Navigation("Parroquia");

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("Entity.Cliente", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("Entity.Constructora", b =>
                {
                    b.Navigation("Cliente")
                        .IsRequired();

                    b.Navigation("Contactos");
                });

            modelBuilder.Entity("Entity.Contacto", b =>
                {
                    b.Navigation("Contactovisita");
                });

            modelBuilder.Entity("Entity.Contrato", b =>
                {
                    b.Navigation("PlanDePagoNavigation");
                });

            modelBuilder.Entity("Entity.Cotizacion", b =>
                {
                    b.Navigation("Cotizaciondetalles");

                    b.Navigation("ImpuestoCotizaciones");

                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("Entity.Empresa", b =>
                {
                    b.Navigation("Empresacorreo");

                    b.Navigation("Empresastorage");

                    b.Navigation("FormatosNumeroCliente");
                });

            modelBuilder.Entity("Entity.Impuesto", b =>
                {
                    b.Navigation("ImpuestoCotizacion");
                });

            modelBuilder.Entity("Entity.Menu", b =>
                {
                    b.Navigation("InverseSecMenuPadreNavigation");

                    b.Navigation("Rolmenus");
                });

            modelBuilder.Entity("Entity.Parroquia", b =>
                {
                    b.Navigation("Visita");
                });

            modelBuilder.Entity("Entity.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Entity.PlanDePago", b =>
                {
                    b.Navigation("Cuotas");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Entity.PlantillaPreContrato", b =>
                {
                    b.Navigation("PlantillaPreContratoParrafos");
                });

            modelBuilder.Entity("Entity.PreContrato", b =>
                {
                    b.Navigation("PreContratoCompromisoPagos");

                    b.Navigation("PreContratoParrafos");
                });

            modelBuilder.Entity("Entity.Provincia", b =>
                {
                    b.Navigation("Cantons");

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("Entity.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Rolmenus");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Entity.Usuario", b =>
                {
                    b.Navigation("Visita");
                });

            modelBuilder.Entity("Entity.Visita", b =>
                {
                    b.Navigation("Contactovisita");
                });
#pragma warning restore 612, 618
        }
    }
}
