CREATE TABLE PlantillaCorreo (
    SecPlantillaCorreo INT PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL,
    Asunto VARCHAR(255) NOT NULL,
    ContenidoHTML TEXT NOT NULL,
    EstaActivo SMALLINT NOT NULL DEFAULT 1,
    FechaRegistro DATETIME DEFAULT CURRENT_TIMESTAMP
);
