INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 1, 'CONTRATO DE EJECUCIÓN DE OBRAS TECMEIN CIA. LTDA. TEC- YDK2503025 PARA LA COMPRA-VENTA, INSTALACIÓN Y PUESTA EN MARCHA DE UN (1) ASCENSOR DE PASAJEROS, PARA EL EDIFICIO TERRA MANABA DE LA CIUDAD DE QUITO', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 2, 'En la Ciudad de Quito, a los 03 días del mes de julio del 2025, comparecen, por una parte, TECMEIN CÍA. LTDA. RUC 1792582962001, debida y legalmente representada por su GERENTE, el Sr. David Raúl Remache Quinahuano, con C.C. 1716767775, parte a la que se le denominará EL CONTRATISTA; y por otra parte, Maritza Elizabeth Patiño Almeida, con RUC.: 1712782836001, parte a la que se le denominará EL CONTRATANTE, ambos mayores de edad y capaces obtener derechos y contraer obligaciones, quienes convienen libre y voluntariamente en suscribir el presente contrato al tenor de las siguientes cláusulas:', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 3, 'PRIMERA. ANTECEDENTES', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 4, 'El CONTRATANTE es promotor del proyecto denominado EDIFICIO TERRA MANABA, ubicado en la de la ciudad de Quito.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 5, 'EL CONTRATISTA distribuye e instala para el Ecuador ascensores de la marca FUJI-YIDA, y brinda el mantenimiento correspondiente para su normal funcionamiento.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 6, 'A fin de preparar la propuesta técnico-económica para la instalación y operación del ascensor, EL CONTRATISTA visitó el Edificio Terra Manaba en la ciudad de Quito, en donde, con la presencia del CONTRATANTE, registró la infraestructura física, en particular, las características del pozo y de las CUATRO plantas a las que servirá el ascensor.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 7, 'SEGUNDA. OBJETO', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 8, 'EL CONTRATISTA vende, instala y una vez en operación dará en perpetua enajenación a favor de EL CONTRATANTE un (1) ascensor marca FUJI-YIDA, de tecnología japonesa, con todos sus componentes originales de fábrica.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 9, 'TERCERA. ESPECIFICACIONES TÉCNICAS', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 10, 'Las especificaciones técnicas del ascensor de pasajeros para el Edificio Terra Manaba, son las siguientes:', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 11, 'Equipo:
• Motor: Sincrónico de imanes permanente. Gearless sin engranaje para alto tráfico. Sin cuarto de máquinas Motor tracción 2:1
• Capacidad: 630 kg
• Ducto: 1800*1800 mm (ancho * fondo)
• Velocidad: 1 m/s.
• Número de paradas: 4 paradas
• Entradas frontales: 4 entradas
• Número de pasajeros: 8 personas
• Recorrido: 15 metros aproximadamente
• Ubicación de las máquinas: Máquinas ubicadas dentro del ducto del edificio.
• Control de maniobra: VVVF (variación simultánea de voltaje y frecuencia), selectiva en descenso.
• Voltaje de operación: 220 V Trifásico.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 12, 'Ascensor
• Cabina: 1100 * 1400*2300 mm (ancho*fondo* altura) en Acero Inoxidable
• Puertas: PB: Acero Inoxidable con marcos anchos. Demás pisos en acero inoxidable y marcos delgados.
• Dimensiones puertas: 800mm*2100 mm
• Accionamiento Puertas: Automáticas de Apertura lateral.
• Operador de puertas: VVVF, con potenciómetros electrónicos de ajuste de velocidad de cierre y apertura de puerta, la cual se podrá variar de acuerdo a las necesidades de tráfico. Con una operación suave, segura y silenciosa.
• Ventilación: Sistema axial ubicado en el techo de cabina.
• Piso: De vinil de 2 mm, instalado y provisto por el Contratista
• Botonera de cabina: Panel fabricado en acero inoxidable cepillado, indicador de pisos digital que indica la posición actual del ascensor, botones de llamadas tipo micro deslizamiento luminoso y con sistema braille, botones de operación de puertas y botón de emergencia.
• Botoneras de pisos: Panel de acero inoxidable montado en el amuramiento de los marcos y con los botones de micro-movimiento luminosos, que muestra la ubicación actual del ascensor.
• Foto celda: Banda con sensores múltiples de rayos infrarrojos de piso a techo: Las puertas se abren automáticamente al interponerse algún cuerpo extraño.
• Intercomunicador: Permite la comunicación entre los pasajeros y el personal de seguridad o administración del edificio
• Rescate de emergencia: Realiza una nivelación de emergencia en caso de corte de energía permitiendo salir a los pasajeros hasta que ésta se restaure.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 13, 'CUARTA. CONFORMIDAD SOBRE LAS ESPECIFICACIONES TÉCNICAS', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 14, 'EL CONTRATANTE afirma que ha sido informado por la CONTRATISTA. sobre las características de los equipos detallados en la cláusula Tercera, por lo que su instalación obedecerá siempre a criterios estrictamente técnicos, primando aspectos de seguridad de los usuarios aún por sobre los estéticos.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 15, 'EL CONTRATANTE, respetará y cumplirá los PLANOS ELÉCTRICOS, CONDICIONES DEL POZO Y ESPECIFICACIONES TÉCNICAS proporcionadas por EL CONTRATISTA, para la instalación del equipo proveniente de fábrica.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 16, 'EL CONTRATANTE proporcionara los siguientes requerimientos para la buena manipulación, bodegaje e instalación del equipo:
• Bodega de 10 x 10 metros', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 17, '• Iluminación en bodega cerrada y toma corriente
• Caja térmica en el ducto para alimentación del ascensor
• Alimentación de 110-220 para instalación del ascensor
• Ducto blanqueado
• Posterior a la instalación de los marcos de puertas, el corchado de las entradas.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 18, 'QUINTA. PLAZO', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 19, 'El plazo para el montaje, instalación y puesta en marcha del ascensor es al término de 180 días, siempre y cuando EL CONTRATANTE haya habilitado la energía eléctrica requerida y la obra civil esté concluida, según las especificaciones técnicas requeridas para el montaje, instalación, puesta en marcha y posterior mantenimiento del ascensor.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 20, 'La fabricación, importación, instalación y puesta en operación del ascensor, será dentro del término de 180 días, contados a partir de una vez recibido el anticipo en su totalidad.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 21, 'El CONTRATISTA entregará todos los equipos y materiales en el tiempo detallado en el cronograma, siempre y cuando EL CONTRATANTE haya concluido la obra civil según los planos entregados por parte de fábrica a través de EL CONTRATISTA; y, el fiel cumplimiento de todos los pagos según cronograma, como se estipula en la Séptima Cláusula del presente contrato.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 22, 'Cualquier circunstancia de obra civil o requerimientos que necesite el ducto de la cuál sea responsable EL CONTRATANTE y que cause retraso en la instalación y puesta en marcha del ascensor, EL CONTRATISTA, extenderá el plazo estipulado en un número igual de días para la instalación del equipo vendido.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 23, 'EL CONTRATISTA elaborará los planos definitivos para la instalación de los equipos. Los planos y especificaciones técnicas que se entreguen al CONTRATANTE se entenderán aceptados en un plazo de treinta (30) días de haberlos recibido, aun cuando tales planos no fueren firmados por EL CONTRATANTE.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 24, 'Si de suscitarse algún caso fortuito o de fuerza mayor, debidamente comprobado, por lo que EL CONTRATISTA no pudiese cumplir con las fechas y lo establecido en el cronograma, éste tendrá un tiempo extensivo para la entrega, montaje, instalación y puesta en marcha del ascensor, correspondiente a los mismos días de retraso que se produjeren por el mencionado caso fortuito o fuerza mayor.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 25, 'La fuerza mayor o caso fortuito no dará derecho al Contratista a solicitar el reconocimiento de mayores costos de indemnizaciones.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 26, 'SEXTA. PRECIO', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 27, 'El precio de los bienes y servicios contratados es de USD $ 34.500,00 Treinta y cuatro mil quinientos con 00/100 (DÓLARES AMERICANOS) el valor incluido IVA. Este valor incluye todos los costos correspondientes al equipo, seguros de transporte, trámites de importación, derechos de importación, desaduanización, transporte interno y descargue de los equipos, honorarios de agente afianzado de aduana, instalación y ajuste de los equipos, etc.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 28, 'En general, el referido valor abarca todo lo relacionado con la provisión, instalación y puesta en funcionamiento del ascensor; en consecuencia, el PRECIO SEÑALADO es FIJO, INALTERABLE y no variará por concepto alguno, salvo por decretos gubernamentales, gastos adicionales de bodegaje o usos de contenedores fuera de tiempo causados por demoras imputables a EL CONTRATANTE y/o nuevos impuestos que afecten a EL CONTRATISTA.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 29, 'SÉPTIMA. FORMA DE PAGO', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 30, 'EL CONTRATANTE pagará al CONTRATISTA la totalidad del precio pactado en la siguiente forma:', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 31, 'Descripción
50% Junto con la firma del contrato: $10.000,00
A 30 días de la firma del contrato la diferencia: $7.250,00
50% Se cancelará los valores en 10 cuotas mensuales, siendo la primera cuota al siguiente mes de la firma del contrato
Primera cuota (03/09/2025): $1.725,00
Segunda cuota (03/10/2025): $1.725,00
Tercera cuota (03/11/2025): $1.725,00
Cuarta cuota (03/12/2025): $1.725,00
Quinta cuota (03/01/2026): $1.725,00
Sexta cuota (03/02/2026): $1.725,00
Séptima cuota (03/03/2026): $1.725,00
Octava cuota (03/04/2026): $1.725,00
Novena cuota (03/05/2026): $1.725,00
Decima cuota (03/06/2026): $1.725,00
TOTAL: $ 34.500,00 (Valor incluido I.V.A.)', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 32, 'OCTAVO. GARANTÍA DE FUNCIONAMIENTO', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 33, 'EL CONTRATISTA y el fabricante garantizan los equipos e implementos materia de este Contrato, contra defectos de fabricación o mala instalación de los mismos por el término de CINCO (5) AÑOS, contados a partir de la fecha en que se suscriba la respectiva acta de entrega-recepción definitiva, siempre y cuando el mantenimiento sea prestado por EL CONTRATISTA. Esta garantía cubre todos los riesgos relativos a mala fabricación, defectos de partes y piezas y mala instalación de los equipos a excepción de daños que se produzcan en partes expuestas al público para su uso, o partes expuestas o no al público pero que se originen en acciones u omisiones del personal de empleados del edificio, o en acciones u omisiones dolosas de terceras personas y por casos fortuitos o de fuerza mayor.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 34, 'Quedan excluidos los defectos que puedan presentarse del desgaste normal, negligencia, uso inapropiado, deficiencia de la energía eléctrica o condiciones anormales del medio ambiente, tales como: sol directo, lluvia o exceso de humedad, temperatura excesiva, gases corrosivos, etc.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 35, 'NOVENA. MANTENIMIENTO', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 36, 'El CONTRATISTA, se compromete con EL CONTRATANTE, a mantenerlo informado sobre el estado de los procesos mientras dura la ejecución del contrato y a entregar los equipos en pleno y perfecto estado de funcionamiento y con todas las normas de seguridad establecidas en los equipos de transporte vertical.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 37, 'El mantenimiento del ascensor lo realizará exclusivamente EL CONTRATISTA en los siguientes términos:', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 38, 'a.) El mantenimiento comprenderá todas y cada una de las operaciones mecánicas, eléctricas y otras que sean necesarias para asegurar un correcto funcionamiento de los ascensores, así como la provisión de los repuestos requeridos, implementos éstos que serán originales de marca FUJI-YIDA y/o aprobados por ella y también la provisión de personal técnicamente calificado para el mantenimiento.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 39, 'b.) El mantenimiento en la forma antes especificada lo hará gratuitamente EL CONTRATISTA por el plazo de TRES (03) meses, a partir de la fecha en que se suscriba la respectiva acta de entrega-recepción definitiva. Una vez concluido el tiempo de gratuidad, se ejecutará un contrato adicional para el mantenimiento preventivo.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 40, 'c.) Se excluye de las estipulaciones anteriores sobre mantenimiento gratuito, a partir de la terminación de la instalación, los daños que se produzcan por las causas anotadas en la cláusula OCTAVA.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 41, 'd.) EL CONTRATANTE por su parte y para efecto de la buena conservación y funcionamiento de los ascensores, en especial durante el plazo anteriormente establecido en que EL CONTRATISTA proveerá mantenimiento gratuito, asume la responsabilidad y obligación de asegurarse que en caso de interrupción del servicio de los ascensores ninguna persona que no sea un representante debidamente autorizado de EL CONTRATISTA manipule ningún mecanismo de los equipos en su afán de repararlo.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 42, 'e.) EL CONTRATISTA mantendrá a disposición de EL CONTRATANTE en forma permanente un servicio de reparaciones.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 43, 'f.) De mutuo acuerdo EL CONTRATANTE y EL CONTRATISTA suscribirán un contrato de mantenimiento, posterior a los TRES (03) meses de instalados los equipos en los términos arriba estipulados para el efecto.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 44, 'g.) La recepción del ascensor se realizará por parte del CONTRATANTE a la notificación de que el equipo se encuentra terminado y listo para su entrega. Empezando en esta fecha el mantenimiento gratuito ofrecido en la cláusula correspondiente.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 45, 'DECIMA. CONTROVERSIA', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 46, 'En caso de suscitarse controversia o diferencia de algún tipo, derivada de este contrato, las partes se someterán a un dialogo voluntario, en el que se tratará de llegar a un acuerdo que favorezca equitativamente a las partes, de no obtener ninguna solución se someterán a la Comisión de Mediación y Arbitraje de la Cámara de Comercio (CCL) de Quito. De ser pertinente acatarán la resolución de los Jueces competentes con residencia en Quito, y se sujetarán a lo que establece la ley en estos casos.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 47, 'DÉCIMA PRIMERA. MANO DE OBRA', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 48, 'EL CONTRATISTA acepta y declara que la contratación del personal necesario para la ejecución de la instalación de los equipos es de su exclusiva responsabilidad, por tanto, los trabajadores que se utilicen para el cumplimiento de este contrato serán contratados y laborarán en relación de dependencia de EL CONTRATISTA.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 49, 'EL CONTRATISTA se exige a cumplir con todas las obligaciones laborales del personal que contrate o llegaré a contratar para el cabal cumplimiento del presente Contrato. El Contratista asume todas las obligaciones derivadas del Código del Trabajo y de la ley de Seguridad Social, por el personal que emplee para cumplir con la prestación del servicio convenido en el Contrato, sin que la Contratante tenga responsabilidad alguna ni relación laboral sobre tales obligaciones.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 50, 'DECIMA SEGUNDA. HOJA DE REPORTES DE ACABADOS', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 51, 'Los detalles y acabados del equipo serán conforme lo mencionado en el anexo de hoja de reportes de acabados, mismos que se respetarán y serán definitivos para la recepción de obra.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 52, 'DECIMA TERCERA. MODIFICACIONES', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 53, 'Cualquier modificación que las partes por mutuo acuerdo deseen hacer a las estipulaciones contenidas en este instrumento, deberá realizarse por escrito y mediante un adendum, mismo que formará parte de este Contrato, sin esta formalidad, todo cambio se reputará inexistente.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 54, 'DECIMA CUARTA. DOMICILIO', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 55, 'Para todos los efectos de este Contrato, las partes convienen en señalar su domicilio en la ciudad de Quito, Vaca de castro y Pedro Freile Email: fruteiro2010@hotmail.com', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 56, 'TECMEIN CIA. LTDA. QUITO. Dir.: Av. La Prensa N50-107 y Tnte. Homero Salas. Telf.: 02- / 3824603 / 3824604 Email: gerencia@tecmein.com', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 57, 'DECIMA QUINTA: ACEPTACIÓN', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 58, 'Este contrato entrará en vigencia desde el momento de suscripción del mismo, DEL CONTRATISTA declara que serán por su cuenta los gastos que se ocasionen en cualquier tipo de inscripción del presente contrato.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 59, 'Las partes libre y voluntariamente dan expresa conformidad a los términos de este contrato y una vez leído y aprobado por cada una de las mismas, proceden aprobar y firmar por duplicado en 6 hojas útiles, en la ciudad de Quito al 03 de julio del 2025.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 60, 'DAVID RAÚL REMACHE QUINAHUANO
EL CONTRATISTA
171676777-5
TECMEIN CÍA. LTDA.', 1);
INSERT INTO PlantillaPreContratoParrafo (SecPlantillaPreContrato, Orden, Contenido, EstaActivo) VALUES (6, 61, 'MARITZA ELIZABETH PATIÑO ALMEIDA
EL CONTRATANTE
C.C.: 1712782836001
EDIFICIO TERRA MANABA', 1);